"""Monitoring: weekly digest report generator."""
from __future__ import annotations

import logging
from datetime import datetime, timezone
from pathlib import Path
from typing import Optional

import aiosqlite

from agent.config.settings import settings

logger = logging.getLogger(__name__)


async def generate_weekly_digest(
    db_path: Optional[str] = None,
) -> str:
    """Generate a Markdown weekly digest report.

    Args:
        db_path: Path to SQLite database.

    Returns:
        Markdown string of the weekly digest.
    """
    if db_path is None:
        db_path = str(settings.data_dir / "psa.db")

    now = datetime.now(timezone.utc)
    week_ago = now.strftime("%Y-%m-%dT%H:%M:%SZ")

    async with aiosqlite.connect(db_path) as conn:
        conn.row_factory = aiosqlite.Row

        # Total experiments
        cursor = await conn.execute("SELECT COUNT(*) FROM experiments")
        total_experiments = (await cursor.fetchone())[0]

        # Successful experiments
        cursor = await conn.execute("SELECT COUNT(*) FROM experiments WHERE status = 'success'")
        successful = (await cursor.fetchone())[0]

        # Total lessons
        cursor = await conn.execute("SELECT COUNT(*) FROM lessons")
        total_lessons = (await cursor.fetchone())[0]

        # Average reward
        cursor = await conn.execute("SELECT AVG(reward) FROM lessons WHERE reward > 0")
        avg_reward_row = await cursor.fetchone()
        avg_reward = avg_reward_row[0] if avg_reward_row[0] else 0.0

        # Top 10 lessons
        cursor = await conn.execute(
            """SELECT technique_name, improvement_pct, reward, source_title, source_url
               FROM lessons ORDER BY reward DESC LIMIT 10"""
        )
        top_lessons = [dict(r) for r in await cursor.fetchall()]

    success_rate = (successful / total_experiments * 100) if total_experiments > 0 else 0.0

    # Build report
    lines = [
        f"# Weekly Digest — {now.strftime('%Y-%m-%d')}",
        "",
        "## Overview",
        "",
        f"| Metric | Value |",
        f"|--------|-------|",
        f"| Total Experiments | {total_experiments} |",
        f"| Successful | {successful} |",
        f"| Success Rate | {success_rate:.1f}% |",
        f"| Lessons Stored | {total_lessons} |",
        f"| Average Reward | {avg_reward:.4f} |",
        "",
        "## Top 10 Techniques This Week",
        "",
        "| # | Technique | Improvement | Reward | Source |",
        "|---|-----------|-------------|--------|--------|",
    ]

    for i, lesson in enumerate(top_lessons, 1):
        lines.append(
            f"| {i} | {lesson['technique_name'][:35]} | "
            f"+{lesson['improvement_pct']:.1f}% | "
            f"{lesson['reward']:.3f} | "
            f"[link]({lesson.get('source_url', '#')}) |"
        )

    lines.extend(["", "---", f"*Generated by perpetual-scholar-agent on {now.isoformat()}*"])

    return "\n".join(lines)


async def save_weekly_digest(
    output_dir: Optional[str] = None,
    db_path: Optional[str] = None,
) -> str:
    """Generate and save the weekly digest to a Markdown file.

    Args:
        output_dir: Directory to save the report.
        db_path: Path to SQLite database.

    Returns:
        Path to the saved report file.
    """
    if output_dir is None:
        output_dir = str(settings.data_dir / "reports")

    digest = await generate_weekly_digest(db_path)

    now = datetime.now(timezone.utc)
    filename = f"digest_{now.strftime('%Y%m%d')}.md"
    output_path = Path(output_dir) / filename

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(digest, encoding="utf-8")

    logger.info(f"Weekly digest saved to {output_path}")
    return str(output_path)
